export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED';

export const ADD_INGREDIENT: 'ADD_INGREDIENT' = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT: 'REMOVE_INGREDIENT' = 'REMOVE_INGREDIENT';
export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN';

export const SWAP_INGREDIENTS: 'SWAP_INGREDIENTS' = 'SWAP_INGREDIENTS';

export const GET_INGREDIENT_DETAILS: 'GET_INGREDIENT_DETAILS' = 'GET_INGREDIENT_DETAILS';
export const REMOVE_INGREDIENT_DETAILS: 'REMOVE_INGREDIENT_DETAILS' = 'REMOVE_INGREDIENT_DETAILS';

export const REMOVE_SELECTED_INGREDIENTS: 'REMOVE_SELECTED_INGREDIENTS' = 'REMOVE_SELECTED_INGREDIENTS';

export const TAB_SWITCH: 'TAB_SWITCH' = 'TAB_SWITCH';