export const WS_PROFILE_CONNECTION_START: 'WS_PROFILE_CONNECTION_START' = 'WS_PROFILE_CONNECTION_START';
export const WS_PROFILE_CONNECTION_SUCCESS: 'WS_PROFILE_CONNECTION_SUCCESS' = 'WS_PROFILE_CONNECTION_SUCCESS';
export const WS_PROFILE_CONNECTION_ERROR: 'WS_PROFILE_CONNECTION_ERROR' = 'WS_PROFILE_CONNECTION_ERROR';
export const WS_PROFILE_CONNECTION_CLOSED: 'WS_PROFILE_CONNECTION_CLOSED' = 'WS_PROFILE_CONNECTION_CLOSED';
export const WS_PROFILE_GET_MESSAGE: 'WS_PROFILE_GET_MESSAGE' = 'WS_PROFILE_GET_MESSAGE';
export const GET_PROFILE_ORDER_BY_ID: 'GET_PROFILE_ORDER_BY_ID' = 'GET_PROFILE_ORDER_BY_ID';
export const HIDE_MODAL_PROFILE: 'HIDE_MODAL_PROFILE' = 'HIDE_MODAL_PROFILE';
export const SHOW_ORDER_PROFILE_DETAILS: 'SHOW_ORDER_PROFILE_DETAILS' = 'SHOW_ORDER_PROFILE_DETAILS';